"""Add BGBEmbedding model

Revision ID: dcbd9fceaea3
Revises: 
Create Date: 2025-12-07 00:17:17.737421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'dcbd9fceaea3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bgb_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=20), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('book_title', sa.String(length=255), nullable=True),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('division_title', sa.String(length=255), nullable=True),
    sa.Column('section_title', sa.Integer(), nullable=True),
    sa.Column('section_title_text', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('contextual_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=False),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bgb_embeddings_book_division', 'bgb_embeddings', ['book', 'division'], unique=False)
    op.create_index('idx_bgb_embeddings_section_number', 'bgb_embeddings', ['section_number'], unique=False)
    op.create_index(op.f('ix_bgb_embeddings_book'), 'bgb_embeddings', ['book'], unique=False)
    op.create_index(op.f('ix_bgb_embeddings_division'), 'bgb_embeddings', ['division'], unique=False)
    op.create_index(op.f('ix_bgb_embeddings_id'), 'bgb_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_bgb_embeddings_section_number'), 'bgb_embeddings', ['section_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bgb_embeddings_section_number'), table_name='bgb_embeddings')
    op.drop_index(op.f('ix_bgb_embeddings_id'), table_name='bgb_embeddings')
    op.drop_index(op.f('ix_bgb_embeddings_division'), table_name='bgb_embeddings')
    op.drop_index(op.f('ix_bgb_embeddings_book'), table_name='bgb_embeddings')
    op.drop_index('idx_bgb_embeddings_section_number', table_name='bgb_embeddings')
    op.drop_index('idx_bgb_embeddings_book_division', table_name='bgb_embeddings')
    op.drop_table('bgb_embeddings')
    # ### end Alembic commands ###

